---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: shobana29/python:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: FLASK_APP
              value: userapi.py
            - name: MYSQL_SERVICE_PORT
              value: "3306"
            - name: MYSQL_SERVICE_HOST
              value: SQLDATA
            - name: db_name
              value: test_database
            - name: db_root_password
              value: root
